### ISSUE TITLE
Implement energy efficiency of machines

### ISSUE THREAD

**Issue by Peter-JanGootzen** [Peter-JanGootzen/vu-ds-energy-aware-scheduling#1]
`ClusterManager.kt` in wta-sim has machines sorted by power efficiency, when scheduling a task in LookAhead it gets the most efficient machine avail and then checks if it fits.
`Machine.kt` `HostSpec.kt` in OpenDC should have something like:
`powerEfficiency = (TDP.toDouble() / numberOfCpus) * normalizedSpeed`

OpenDC has no notion of TDP, normalizedspeed (just a normalization of all the baseclocks) or power effiency.
Add something somewhere, follow the trail from `NewFlavor` `HostSpec`.

**Comment by bwesterveld** [comment]
TDP and other energy related metrics can be stored in the metadata of tasks so we can access it in the scheduler.
