### ISSUE TITLE
Implement metrics

### ISSUE THREAD

**Issue by Peter-JanGootzen** [Peter-JanGootzen/vu-ds-energy-aware-scheduling#6]
See `WebComputeMonitor.kt`

**Comment by bwesterveld** [comment]
Currently, the idleTime is negative and equal to the activeTime.

**Comment by Peter-JanGootzen** [comment]
What metrics does Capelin monitor?

Actual metrics reader: **ComputeMetricReader Writes** to disk via **ParquetComputeMonitor**

Host metrics:
_timestamp = now
_guestsTerminated = hostSysStats.guestsTerminated
_guestsRunning = hostSysStats.guestsRunning
_guestsError = hostSysStats.guestsError
_guestsInvalid = hostSysStats.guestsInvalid
_cpuLimit = hostCpuStats.capacity
_cpuDemand = hostCpuStats.demand
_cpuUsage = hostCpuStats.usage
_cpuUtilization = hostCpuStats.utilization
_cpuActiveTime = hostCpuStats.activeTime
_cpuIdleTime = hostCpuStats.idleTime
_cpuStealTime = hostCpuStats.stealTime
_cpuLostTime = hostCpuStats.lostTime
_powerUsage = hostSysStats.powerUsage
_powerTotal = hostSysStats.energyUsage
_uptime = hostSysStats.uptime.toMillis()
_downtime = hostSysStats.downtime.toMillis()
_bootTime = hostSysStats.bootTime

Server (VM) metrics:
_cpuLimit = cpuStats?.capacity ?: 0.0
_cpuActiveTime = cpuStats?.activeTime ?: 0
_cpuIdleTime = cpuStats?.idleTime ?: 0
_cpuStealTime = cpuStats?.stealTime ?: 0
_cpuLostTime = cpuStats?.lostTime ?: 0
_uptime = sysStats?.uptime?.toMillis() ?: 0
_downtime = sysStats?.downtime?.toMillis() ?: 0
_provisionTime = _server.launchedAt
_bootTime = sysStats?.bootTime

SchedulerStats from the ComputeService which orchestrates the ComputeScheduler:
_hostsUp = stats.hostsAvailable
_hostsDown = stats.hostsUnavailable
_serversTotal = stats.serversTotal
_serversPending = stats.serversPending
_serversActive = stats.serversActive
_attemptsSuccess = stats.attemptsSuccess.toInt()
_attemptsFailure = stats.attemptsFailure.toInt()
_attemptsError = stats.attemptsError.toInt()

**Comment by skip-th** [comment]
We can retrieve the energy and cpu utilization metrics over multiple scheduler cycles.
