### ISSUE TITLE
Implement slack-based scheduling as TaskEligibilityPolicy

### ISSUE THREAD

**Issue by Peter-JanGootzen** [Peter-JanGootzen/vu-ds-energy-aware-scheduling#8]
In `WorkFlowService:doSchedule` the `taskEligibilityPolicy` is used to determine which tasks need to be given to the ComputeScheduler (#5)

**Comment by bwesterveld** [comment]
Jobs can have multiple tasks. Tasks within a job may have dependencies. The metadata of tasks should be extended with the calculated slack. A job can be fetched from a queue of `JobState` objects which has a set of `TaskState` objects. A `TaskState` object has a public `Task` object where this metadata resides.

To populate the metadata, we can modify the `Trace.toJobs()` function in `TraceHelpers.kt` or `WorkflowService.replay()` function in `TraceHelpers.kt` to calculate and store the slack. As `Trace.toJobs()` already calculates dependencies, this might have the preference.

In the following snippets, Jobs with many Tasks are admitted at marker AAAA.
Tasks can be admitted when they have low slack which is checked at marker BBBB.

WorkflowServiceImpl.kt

    private fun doSchedule() {
        // J2 Create list of eligible jobs
        val iterator = incomingJobs.iterator()
        while (iterator.hasNext()) {
            val jobInstance = iterator.next()
            val advice = jobAdmissionPolicy(jobInstance)
            if (advice.stop) {
                break
            } else if (!advice.admit) {
                continue
            }
            iterator.remove()
            jobQueue.add(jobInstance)
            activeJobs += jobInstance

            _workflowsRunning++
            rootListener.jobStarted(jobInstance)
        }

        // J4 Per job
        // Marker AAAA
        while (true) {
            val jobInstance = jobQueue.poll() ?: break

            // Edge-case: job has no tasks
            if (jobInstance.isFinished) {
                finishJob(jobInstance)
            }

            // Add job roots to the scheduling queue
            for (task in jobInstance.tasks) {
                if (task.state != TaskStatus.READY) {
                    continue
                }

                incomingTasks += task
                rootListener.taskReady(task)
            }
        }

        // T1 Create list of eligible tasks
        val taskIterator = incomingTasks.iterator()
        while (taskIterator.hasNext()) {
            val taskInstance = taskIterator.next()
            // Marker BBBB
            val advice = taskEligibilityPolicy(taskInstance)
            if (advice.stop) {
                break
            } else if (!advice.admit) {
                continue
            }

            taskIterator.remove()
            taskQueue.add(taskInstance)
        }

        // T3 Per task
        while (taskQueue.isNotEmpty()) {
            val instance = taskQueue.peek()

            val cores = instance.task.metadata[WORKFLOW_TASK_CORES] as? Int ?: 1
            val image = image
            scope.launch {
                val flavor = computeClient.newFlavor(
                    instance.task.name,
                    cores,
                    1000
                ) // TODO How to determine memory usage for workflow task
                val server = computeClient.newServer(
                    instance.task.name,
                    image,
                    flavor,
                    start = false,
                    meta = instance.task.metadata
                )

                instance.state = TaskStatus.ACTIVE
                instance.server = server
                taskByServer[server] = instance

                server.watch(this@WorkflowServiceImpl)
                server.start()
            }

            activeTasks += instance
            taskQueue.poll()
            rootListener.taskAssigned(instance)
        }
    }

To create the `TasEligibilityPolicy`, we can take inspiration from the `LimitPerJobTaskEligibilityPolicy`. The invoke function there should have access to the slack information in a task, which should be used to determine whether to admit or deny a task.


LimitPerJobTaskEligibilityPolicy.kt
```
           override fun invoke(task: TaskState): TaskEligibilityPolicy.Advice {
                val activeJobs = scheduler.activeJobs.size
                val activeTasks = scheduler.activeTasks.size
                val baseline = max(activeTasks / activeJobs.toDouble(), 1.0)
                val activeForJob = active[task.job]!!
                return if ((activeForJob + 1) / baseline < tolerance) {
                    TaskEligibilityPolicy.Advice.ADMIT
                } else {
                    TaskEligibilityPolicy.Advice.DENY
                }
            }
```

**Comment by bwesterveld** [comment]
We have determined that the policy should accept all tasks. We will use the NullTaskEligibilityPolicy instead.
